### ISSUE TITLE
API error invalid url no schema supplied

### ISSUE THREAD

**Issue by fabnavigator** [2blane/OctoPrint-Webhooks#20]
Hi,

I'm using "http://192.168.0.140:1881/octoprint" as my url, but keep getting a no schema specified error. What am I doing wrong? I can specify that url in postman and it works.

Thanks,

Bill

**Comment by unclej84** [comment]
Hi,

I had the same error at first - the url has not been saved (see #19 ). You have to hit e.g. "Activate Template" in order to have it saved. Afterwards your it should work. As a workaround I create a copy or new webhook at first before I edit my webhook and delete the copy afterwards. That saves the settings too.

Regards Jörg

**Comment by fabnavigator** [comment]
Thank you. That did the trick.
