### ISSUE TITLE
2.6.0: Always sending content-type: multipart/form-data

### ISSUE THREAD

**Issue by AndyRace** [2blane/OctoPrint-Webhooks#6]
Hi Blane,
No matter what I try, my webhooks are receiving form-data instead of json.
The debugging indicates it's following the JSON path, but https://webhook.site/ (for example) always reports multipart/form-data
I look forward to using this once this is fixed

**Comment by 2blane** [comment]
@AndyRace are you by chance using the @snapshot parameter inside DATA? If so, the content type gets overridden to multiparty/form-data so that the image file can be sent. Haven’t seen anyone send an image file through json/ don’t know if it’s possible so that’s why it works the way it does. Will try to update the UI to make this more clear.

**Comment by AndyRace** [comment]
Hi @2blane, that's exactly what it was 👍 
I just went for the defaults and got bitten :)
Works a treat now

**Comment by 2blane** [comment]
@AndyRace awesome glad to hear it! I’ll make this more clear.
